# Redis
spring.data.redis.host=${REDIS_HOST_URL}
spring.data.redis.port=${PORT_}
spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.ssl.enabled=true

# Topic
spring.cloud.gcp.project-id=${SPRING_CLOUD_GCP_PROJECT_ID}
spring.cloud.task.queue.id=${QUEUE_ID}
spring.cloud.task.queue.region=${QUEUE_REGION}
target.url=ok

# SQL path
sql.path =classpath:sql/find_accepted_followees.sql
