spring.datasource.url=${FOLLOWER_DB_URL}
spring.datasource.username=${FOLLOWER_DB_USERNAME}
spring.datasource.password=${FOLLOWER_DB_PASSWORD}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update



