spring.datasource.url=${FOLLOWER_DB_URL}
spring.datasource.username=${FOLLOWER_DB_USERNAME}
spring.datasource.password=${FOLLOWER_DB_PASSWORD}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none

account-service.url=${ACCOUNT_SERVICE_URL}

spring.cloud.gcp.project-id=${SPRING_CLOUD_GCP_PROJECT_ID}
spring.cloud.gcp.topic=fanout-push

limit.celebrity = 100000




