spring.cassandra.schema-action=CREATE_IF_NOT_EXISTS
spring.cassandra.request.timeout=10s
spring.cassandra.connection.connect-timeout=10s
spring.cassandra.connection.init-query-timeout=10s
spring.cassandra.keyspace-name=posts_write

# Astra DB Configuration
astra.api.application-token=${ASTRA_DB_APPLICATION_TOKEN}
astra.api.database-id=${ASTRA_API_DB_ID}
astra.api.database-region=${ASTRA_API_DB_REGION}
astra.api.cross-region-failback=false

# CQL Configuration
astra.cql.enabled=true
astra.cql.download-scb.enabled=true
astra.cql.driver-config.basic.session-keyspace=posts_write

post-consumer.url = ${POST_CONSUMER_URL}


