# Postgres
spring.datasource.url=${FOLLOWER_DB_REP_BACKFILL_URL}
spring.datasource.username=${FOLLOWER_DB_REP_BACKFILL_USERNAME}
spring.datasource.password=${FOLLOWER_DB_REP_BACKFILL_PASSWORD}

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Redis
spring.data.redis.host=${REDIS_HOST_URL}
spring.data.redis.port=${PORT_}
spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.ssl.enabled=true

# SQL path
sql.path =classpath:sql/find_accepted_followees.sql
