spring.data.redis.url=${REDIS_URL}

spring.datasource.url=${FOLLOWER_BACKFILL_DB_URL}
spring.datasource.username=${FOLLOWER_BACKFILL_DB_USERNAME}
spring.datasource.password=${FOLLOWER_BACKFILL_DB_PASSWORD}

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
