name: Deploy backend

# Trigger workflow on push to main branch
on:
  push:
    branches:
      - main   # change if you use a different branch

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - module: account-service
            service_account: default

          - module: content-service
            service_account: spring-pubsub-publisher@$project-426cf434-d967-43ff-a23.iam.gserviceaccount.com

          - module: post-consumer
            service_account: default

    env:
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      REGION: ${{ secrets.GCP_REGION }}
      REPO_NAME: ${{ secrets.ARTIFACT_REPO }}
      PROJECT_NUMBER: ${{ secrets.PROJECT_NUMBER }}
      WIF_PROVIDER: ${{ secrets.WIF_PROVIDER }}
      DEPLOY_SERVICE_ACCOUNT: ${{ secrets.DEPLOY_SERVICE_ACCOUNT }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      ##- name: Authenticate to Google Cloud (OIDC)
        ##uses: google-github-actions/auth@v1
        ##with:
          ##  workload_identity_provider: ${{ env.WIF_PROVIDER }}
            ##service_account: ${{ env.DEPLOY_SERVICE_ACCOUNT }}

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          create_credentials_file: true
          workload_identity_provider: ${{ env.WIF_PROVIDER }}
          service_account: ${{ env.DEPLOY_SERVICE_ACCOUNT }}

      - name: Configure Docker
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build module
        run: ./gradlew :server:${{ matrix.module }}:clean :server:${{ matrix.module }}:build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run:  docker build -t ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ matrix.module }}:latest server/${{ matrix.module }}

      - name: Push Docker image
        run: docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ matrix.module }}:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ matrix.module }} \
            --image ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ matrix.module }}:latest \
            --region ${{ env.REGION }} \
            --platform managed \
            --allow-unauthenticated \
            --env-vars-file ./server/cloudrun.env