name: Deploy backend

# Trigger workflow on push to main branch
on:
  push:
    branches:
      - main   # change if you use a different branch

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - module: account-service
            service_account: default
          - module: content-service
            service_account: spring-pubsub-publisher@project-426cf434-d967-43ff-a23.iam.gserviceaccount.com
          - module: post-consumer
            service_account: default

    env:
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      REGION: ${{ secrets.GCP_REGION }}
      REPO_NAME: ${{ secrets.ARTIFACT_REPO }}
      PROJECT_NUMBER: ${{ secrets.PROJECT_NUMBER }}

    steps:
      - uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: "projects/${{ secrets.PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github-actions-pool/providers/github"
          service_account: "ci-cd-deployer@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com"

